<a href="https://colab.research.google.com/github/mehmetzorlu/tensowflow_bootcamp/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensor using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python function)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself


# Introduction to Tensors

In [17]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [18]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [19]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [20]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [21]:
# Check the dimension of our vector
vector.ndim

1

In [22]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [23]:
matrix.ndim

2

In [24]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [25]:
# What's the number dimensions of another_matrix
another_matrix.ndim

2

In [26]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [27]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional is a vector)


In [28]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [29]:
#Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
unchangeable_tensor[0] = 7

In [ ]:
unchangeable_tensor[0].assign(7)

## Creating random tensor
Random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal
random_1, random_2, random_1 == random_2

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

In [ ]:
not_shuffled

⚒ **Exercise:** Read through Tensorflow documentation on random see generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensor and shuffle them

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:

> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjuction to determine the random sequence."


In [ ]:
exercise_tensor_1 = tf.constant(5)
tf.random.shuffle(exercise_tensor_1)

In [ ]:
exercise_tensor_2 = tf.constant([5])
tf.random.shuffle(exercise_tensor_2)

In [ ]:
exercise_tensor_3 = tf.constant([5, 7])
tf.random.shuffle(exercise_tensor_3)

In [ ]:
exercise_tensor_4 = tf.constant([[5, 7, 4, 2],
                                 [1, 2, 3, 4]])
tf.random.shuffle(exercise_tensor_4)

In [ ]:
exercise_tensor_5 = tf.constant([[[5, 7, 4, 2],
                                 [1, 2, 3, 4]],
                                 [[1, 1, 4, 4],
                                 [7, 2, 8, 4]]])
tf.random.shuffle(exercise_tensor_5)

### Other ways to make tensors

In [ ]:
# Create a tendor of all ones
tf.ones([10, 7])

In [ ]:
# Create a tensor of all zeroes
tf.zeros(shape=(3,4))

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and Tensorflow is that tensors can be run on a GPU (much faster for numerical computing)


In [32]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A , shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

In [ ]:
A.ndim, B.ndim

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size


In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

### Indexing tensors

Tensors can be indexed just like Python lists.

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
some_list[:1]

In [ ]:
rank_4_tensor.shape

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1]
rank_4_tensor[:1, :1, :1, :1]
rank_4_tensor[:1, :1, :, :1]
rank_4_tensor[:1, :, :1, :1]
rank_4_tensor[:, :1, :1, :1]

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
rank_2_tensor

In [ ]:
some_list, some_list[-1]

In [ ]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor


In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # "-1" means expand the final axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

In [ ]:
rank_2_tensor

### Manipulating tensors (tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`


In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

In [ ]:
# Original tensor is unchanged
tensor

In [ ]:
# Multiplication also works
tensor * 10

In [ ]:
# Subraction if you want
tensor - 10

In [ ]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

In [ ]:
tensor

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common operations.

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimension




In [ ]:
# Matrix multiplicaiton in tensorflow
tf.matmul(tensor, tensor)


In [ ]:
tensor * tensor

In [ ]:
# Matrix multiplicaiton with Python operator "@"
tensor * tensor

In [ ]:
tensor.shape

In [ ]:
# Create a tensor (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

In [ ]:
# Try to matrix multiply tensors of same shape
X @ Y
tf.matmul(X, Y)

📖 **Resource:** Info and example of matrix multioplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html




In [ ]:
Y

In [ ]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2,3))

In [ ]:
X.shape, tf.reshape(Y, shape = (2, 3)).shape

In [ ]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2,3))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

In [ ]:
# Try to matrix multiply X by reshaped Y
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

In [ ]:
tf.reshape(X, shape=(2,3)).shape, Y.shape

In [ ]:
# Can do the same with trnasponse
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

In [ ]:
# Try matrix multiplicaiton with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`
* `@`



In [ ]:
X, Y, tf.transpose(X)

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=1)

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=0)

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))


In [ ]:
tf.matmul(X, tf.transpose(Y))

Generally, when performing matrix multiplicaiton on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satify the matrix multiplicaiton rules.

### Changing the datatype of a tensor

In [ ]:
tf.__version__

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

In [ ]:
C = tf.constant([7, 10])
C, C.dtype

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype= tf.float16)
D, D.dtype

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype


In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.


In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D

In [ ]:
#Get the absolute value
tf.abs(D)

Let's go through the following forms of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

In [ ]:
tf.size(E), E.shape, E.ndim

In [ ]:
# Find the minimum
tf.reduce_min(E), np.min(E)

In [ ]:
# Find the maximum
tf.reduce_max(E)

In [ ]:
# Find the mean
tf.reduce_mean(E)

In [ ]:
# Find the sum
tf.reduce_sum(E)

⚒ **Exercise:** With what we've just learned, find the variance and standard deviation of our `E` tensor using Tensorflow methods.

In [ ]:
# Find the variance
tf.reduce_variance(E) # won't work

In [ ]:
# To find the varianc eof our tensor, we need access to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

In [30]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))


NameError: name 'E' is not defined

In [ ]:
tf.math.reduce_std(E)

In [ ]:
# Find the variance of our E tensor
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

### Find the positional maximum and minimum


In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F= tf.random.uniform(shape=[50])
F

In [ ]:
# Find the positional maximum
tf.argmax(F)

In [ ]:
np.argmax(F)

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

In [ ]:
# Find the max value of F
tf.reduce_max(F)

In [ ]:
# Check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
# Find the positional minimum
tf.argmin(F)

In [ ]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

In [ ]:
G.shape

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

### One hot encoding

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth = 4)

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value ="yo, I love deep learning",  off_value = "I also like to dance")

### Squaring, log ,square root

In [ ]:
# Create a new tensor
H = tf.range(1, 10)
H

In [ ]:
# square it
tf.square(H)

In [ ]:
# Find the square root (will error, method requires non-int type)
tf.sqrt(H)

In [ ]:
# Find the square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

In [ ]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays.

🔑 **Note** One of the main differences between a TensorFlow tensor and a NumPy array is that a TensorFlow tensor can be run in a GPU or TPU (for faster numerical processing)


In [33]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7. , 10. ]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [34]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [35]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [38]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [39]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
!nvidia-smi

Sun Mar  2 09:08:33 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P8             13W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

> 🔑 **Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whneever possible.

### Exercises

In [3]:
# 1. Create a vector, scalar, matrix, and tensor with values of your choosing using tf.constant
vector = tf.constant([4.1, 4.5, 6.7])
scalar = tf.constant(3)
matrix = tf.constant([[.1, .6],
                             [.5, .09]])
tensor = tf.constant([[[1, 2],
                              [5, 1]],
                              [[1, 2],
                              [5, 1]]
                             ])

vector, scalar, matrix, tensor

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4.1, 4.5, 6.7], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.1 , 0.6 ],
        [0.5 , 0.09]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [5, 1]],
 
        [[1, 2],
         [5, 1]]], dtype=int32)>)

In [10]:
# 2. Find the shape, rank, and size of the tensors you created in 1
tf.shape(vector), vector.shape, tf.rank(vector), vector.ndim, tf.size(vector)


tf.shape(scalar), scalar.shape, tf.rank(scalar), scalar.ndim, tf.size(scalar)


tf.shape(matrix), matrix.shape, tf.rank(matrix), matrix.ndim, tf.size(matrix)

tf.shape(tensor), tensor.shape, tf.rank(tensor), tensor.ndim, tf.size(tensor)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 2], dtype=int32)>,
 TensorShape([2, 2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 3,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [20]:
# 3. Create two tensors containing random variables between 0 and 1 with shape [5, 300]
tf.random.set_seed(42)
random1 = tf.random.uniform(minval=0, maxval =1, shape=(5, 300))
random2 = tf.random.uniform(minval=0, maxval=1, shape=(5, 300))

In [21]:
# 4. Multiply the two tensors you created in 3 using matrix multiplicaiton
tf.matmul(random1, tf.transpose(random2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
       [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
       [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
       [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
       [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
      dtype=float32)>

In [25]:
# 5. Multiply the two tensors you created in 3 using dot product
tf.tensordot(random1, tf.transpose(random2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
       [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
       [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
       [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
       [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
      dtype=float32)>

In [2]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
tf.random.set_seed(42)
random_3 = tf.random.uniform(minval=0, maxval = 1, shape=(224, 224, 3))
random_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

In [4]:
# 7. Find the min and max values of the tensor you created in 6
tf.reduce_min(random_3), tf.reduce_max(random_3)

(<tf.Tensor: shape=(), dtype=float32, numpy=3.5762786865234375e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999979734420776>)

In [7]:
# 8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
random_4 = tf.random.uniform(minval = 0, maxval = 1, shape=(1, 224, 224, 3))
random_4
tf.squeeze(random_4)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
        [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
        [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
        ...,
        [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
        [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
        [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],

       [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
        [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
        [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
        ...,
        [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
        [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
        [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],

       [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
        [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
        [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
        ...,
        [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],
        [3.3173549e-01

In [17]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum values
random_5 = tf.constant([1, 3, 88, 22, 12, 33, 55, 66, 10, 12])
tf.argmax(random_5)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [18]:
# 10. One-hot encode the tensor you created in 9
tf.one_hot(random_5, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>